import { expect, test } from '@playwright/test'

test('can navigate all primary modules and create a vehicle', async ({ page }) => {
  await page.goto('/')
  for (const label of ['首页总览', '用车记账', '费用日历', '数据分析', '详细记录', '能耗统计', '车辆管理']) await expect(page.getByRole('link', { name: label })).toBeVisible()
  await page.getByRole('link', { name: '车辆管理' }).click()
  await page.getByRole('button', { name: '新增车辆' }).click()
  await page.getByLabel('车辆名称').fill('测试燃油车')
  await page.getByLabel('初始里程（km）').fill('1000')
  await page.getByRole('button', { name: '保存车辆' }).click()
  await expect(page.getByText('测试燃油车 · 默认车辆')).toBeVisible()
  await page.getByRole('button', { name: '＋记一笔' }).click()
  await page.getByLabel('金额（元）').fill('20')
  await page.getByRole('button', { name: '保存并查看记录' }).click()
  await expect(page.getByText('共 1 笔，合计 ¥20.00')).toBeVisible()
})

test('sorts detailed records by date ascending by default and can switch to descending', async ({ page }) => {
  await page.goto('/vehicles')
  await page.getByRole('button', { name: '新增车辆' }).click()
  await page.getByLabel('车辆名称').fill('排序测试车')
  await page.getByLabel('初始里程（km）').fill('0')
  await page.getByRole('button', { name: '保存车辆' }).click()

  await page.getByRole('button', { name: '＋记一笔' }).click()
  await page.getByLabel('金额（元）').fill('10')
  await page.getByLabel('发生时间').fill('2026-01-02T12:00')
  await page.getByRole('button', { name: '保存并查看记录' }).click()

  await page.getByRole('button', { name: '＋记一笔' }).click()
  await page.getByLabel('金额（元）').fill('20')
  await page.getByLabel('发生时间').fill('2026-01-01T12:00')
  await page.getByRole('button', { name: '保存并查看记录' }).click()

  await expect(page.locator('tbody tr').first()).toContainText('2026年1月1日')
  await page.getByLabel('排序').selectOption('date-desc')
  await expect(page.locator('tbody tr').first()).toContainText('2026年1月2日')

  await page.getByLabel('最低金额').fill('15')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: '清除筛选' }).click()
  await expect(page.getByLabel('最低金额')).toHaveValue('')
  await expect(page.getByLabel('排序')).toHaveValue('date-asc')
  await expect(page.locator('tbody tr')).toHaveCount(2)
  await expect(page.locator('tbody tr').first()).toContainText('2026年1月1日')
})

test('saves and restores a selected fuel grade', async ({ page }) => {
  await page.goto('/vehicles')
  await page.getByRole('button', { name: '新增车辆' }).click()
  await page.getByLabel('车辆名称').fill('油品测试车')
  await page.getByLabel('初始里程（km）').fill('0')
  await page.getByRole('button', { name: '保存车辆' }).click()
  await page.getByRole('button', { name: '＋记一笔' }).click()
  await page.getByRole('button', { name: '加油' }).click()
  await page.getByLabel('金额（元）').fill('100')
  await page.getByLabel('当前里程（km）').fill('1000')
  await page.getByLabel('加油量（升）').fill('10')
  await page.getByLabel('油品标号').selectOption('95号')
  await expect(page.getByLabel('油品标号')).toHaveValue('95号')
  await page.getByRole('button', { name: '保存并查看记录' }).click()
  await page.getByRole('button', { name: '编辑' }).click()
  await expect(page.getByLabel('油品标号')).toHaveValue('95号')
})

test('adapts energy scenes by vehicle type and supports keyboard scene selection', async ({ page }) => {
  await page.goto('/vehicles')
  await page.getByRole('button', { name: '新增车辆' }).click()
  await page.getByLabel('车辆名称').fill('纯电记账车')
  await page.getByLabel('能源类型').selectOption('electric')
  await page.getByLabel('初始里程（km）').fill('0')
  await page.getByRole('button', { name: '保存车辆' }).click()
  await page.getByRole('button', { name: '＋记一笔' }).click()

  await expect(page.getByRole('button', { name: '加油' })).toHaveCount(0)
  const charge = page.getByRole('button', { name: '充电' })
  await charge.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('充电量（kWh）')).toBeVisible()
  await page.getByLabel('充电量（kWh）').fill('20')
  await page.getByLabel('单价（元/kWh）').fill('1.5')
  await expect(page.getByLabel('金额（元）')).toHaveValue('30.00')
  await page.getByLabel('当前里程（km）').fill('100')
  await page.getByLabel('充电方式').selectOption('公共直流快充')
  await page.getByRole('button', { name: '保存并再记一笔' }).click()
  await expect(page.getByText('保存成功，可以继续记账。')).toBeVisible()
  await expect(page.getByLabel('金额（元）')).toHaveValue('')
})
