import { expect, test } from '@playwright/test'

async function addVehicle(page: import('@playwright/test').Page, name: string, type: 'fuel' | 'electric' | 'hybrid') {
  await page.goto('/vehicles')
  await page.getByRole('button', { name: '新增车辆' }).click()
  await page.getByLabel('车辆名称').fill(name)
  await page.getByLabel('能源类型').selectOption(type)
  await page.getByLabel('初始里程（km）').fill('0')
  await page.getByRole('button', { name: '保存车辆' }).click()
}
async function addFuelRecord(page: import('@playwright/test').Page, date: string, mileage: string, liters: string, amount: string, full: boolean) {
  await page.goto('/record')
  await page.getByRole('button', { name: '加油' }).click()
  await page.getByLabel('金额（元）').fill(amount)
  await page.getByLabel('发生时间').fill(date)
  await page.getByLabel('当前里程（km）').fill(mileage)
  await page.getByLabel('加油量（升）').fill(liters)
  if (full) await page.getByLabel('已加满').check()
  await page.getByRole('button', { name: '保存并查看记录' }).click()
}
async function addChargeRecord(page: import('@playwright/test').Page, date: string, mileage: string, kwh: string, amount: string, full: boolean) {
  await page.goto('/record')
  await page.getByRole('button', { name: '充电' }).click()
  await page.getByLabel('金额（元）').fill(amount)
  await page.getByLabel('发生时间').fill(date)
  await page.getByLabel('当前里程（km）').fill(mileage)
  await page.getByLabel('充电量（kWh）').fill(kwh)
  if (full) await page.getByLabel('已充满').check()
  await page.getByRole('button', { name: '保存并查看记录' }).click()
}test('switches energy vehicles, ranges and quick record actions', async ({ page }) => {
  await addVehicle(page, '燃油测试车', 'fuel')
  await addVehicle(page, '纯电测试车', 'electric')
  await page.goto('/energy')

  await expect(page.getByLabel('能耗车辆').locator('option:checked')).toHaveText(/燃油测试车|纯电测试车/)
  await expect(page.getByLabel('能耗时间范围')).toHaveValue('twelve')
  await page.getByLabel('能耗车辆').selectOption({ label: '燃油测试车' })
  await expect(page.getByRole('link', { name: '记录加油' })).toBeVisible()
  await expect(page.getByRole('link', { name: '记录充电' })).toHaveCount(0)

  await page.getByLabel('能耗车辆').selectOption({ label: '纯电测试车' })
  await expect(page.getByRole('link', { name: '记录充电' })).toBeVisible()
  await page.getByLabel('能耗时间范围').selectOption('custom')
  await expect(page.getByLabel('能耗开始日期')).toBeVisible()
  await expect(page.getByLabel('能耗结束日期')).toBeVisible()

  await page.getByLabel('当前车辆').selectOption('all')
  await expect(page.getByText('请选择一辆具体车辆查看能耗统计。')).toBeVisible()
  await expect(page.getByLabel('选择能耗车辆')).toBeVisible()
})
test('shows weighted fuel metrics, quality and no misleading zero values', async ({ page }) => {
  await addVehicle(page, '能耗计算车', 'fuel')
  await addFuelRecord(page, '2026-08-01T10:00', '1000', '50', '250', true)
  await addFuelRecord(page, '2026-08-10T10:00', '1200', '20', '100', false)
  await addFuelRecord(page, '2026-08-20T10:00', '1500', '25', '125', true)
  await page.goto('/energy')

  await expect(page.getByText('平均油耗')).toBeVisible()
  await expect(page.locator('.metric').filter({ hasText: '平均油耗' })).toContainText('9.00 L/100km')
  await expect(page.locator('.metric').filter({ hasText: '最近油耗' })).toContainText('9.00 L/100km')
  await expect(page.locator('.metric').filter({ hasText: '每公里燃油成本' })).toContainText('¥0.45/km')
  await expect(page.locator('.metric').filter({ hasText: '平均油价' })).toContainText('¥5.00/L')
  await expect(page.getByText('有效完整区间：1')).toBeVisible()
  await expect(page.getByText('未标记加满：1')).toBeVisible()
  await expect(page.getByRole('img', { name: '油耗趋势图' })).toBeVisible()
  await expect(page.getByText('加权平均：9.00 L/100km')).toBeVisible()
  await expect(page.getByRole('img', { name: '油价趋势图' })).toBeVisible()
  const intervalTable = page.getByRole('table', { name: '油耗区间明细' })
  await expect(intervalTable).toBeVisible()
  await expect(intervalTable.getByRole('row').nth(1)).toContainText('2026年8月1日 → 2026年8月20日')
  const trendPoint = page.getByRole('button', { name: /查看区间.*2026年8月20日/ })
  await trendPoint.focus()
  await expect(trendPoint).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('status')).toContainText('已选择区间：2026年8月20日')
  const basis = page.getByRole('region', { name: '区间计算依据' })
  await expect(basis).toContainText('计算基准（起始边界）：2026年8月1日 · 1000 km')
  await expect(basis).toContainText('区间内补能：2026年8月10日 · 20.00 L')
  await expect(basis).toContainText('结束边界：2026年8月20日 · 25.00 L')
  await expect(page.getByText('0.00 L/100km')).toHaveCount(0)
})
test('edits, excludes and restores energy records with persistence', async ({ page }) => {
  await addVehicle(page, '补能记录车', 'fuel')
  await addFuelRecord(page, '2026-08-20T10:00', '1500', '25', '125', true)
  await page.goto('/energy')

  const filter = page.getByLabel('补能记录筛选')
  await filter.selectOption('valid')
  await page.getByRole('button', { name: '编辑2026年8月20日加油记录' }).click()
  const dialog = page.getByRole('dialog', { name: '编辑补能记录' })
  await dialog.getByLabel('金额（元）').fill('130')
  await dialog.getByRole('button', { name: '保存更改' }).click()
  await expect(page.getByRole('table', { name: '补能记录' })).toContainText('¥130.00')

  await page.getByRole('button', { name: '排除2026年8月20日加油记录' }).click()
  await expect(page.getByText('没有符合当前筛选的补能记录。')).toBeVisible()
  await filter.selectOption('excluded')
  await expect(page.getByRole('table', { name: '补能记录' })).toContainText('已排除')

  await page.reload()
  const excludedRow = page.getByRole('table', { name: '补能记录' }).getByRole('row').filter({ hasText: '2026年8月20日' })
  await expect(excludedRow).toContainText('已排除')
  await excludedRow.getByRole('button', { name: '恢复2026年8月20日加油记录' }).click()
  await expect(excludedRow).toContainText('参与计算')
  await page.reload()
  await expect(page.getByRole('table', { name: '补能记录' }).getByRole('row').filter({ hasText: '2026年8月20日' })).toContainText('参与计算')
})
test('shows independent hybrid trends and combined energy cost without fake combined consumption', async ({ page }) => {
  await addVehicle(page, '插混测试车', 'hybrid')
  await addFuelRecord(page, '2026-08-01T10:00', '1000', '50', '250', true)
  await addChargeRecord(page, '2026-08-02T10:00', '1100', '30', '30', true)
  await addFuelRecord(page, '2026-08-20T10:00', '1500', '40', '200', true)
  await addChargeRecord(page, '2026-08-21T10:00', '1600', '60', '60', true)
  await page.goto('/energy')

  await expect(page.locator('.metric').filter({ hasText: '平均油耗' })).toContainText('8.00 L/100km')
  await expect(page.locator('.metric').filter({ hasText: '平均电耗' })).toContainText('12.00 kWh/100km')
  await expect(page.locator('.metric').filter({ hasText: '综合能源成本' })).toContainText('¥0.43/km')
  await expect(page.locator('.metric').filter({ hasText: '燃油费用占比' })).toContainText('¥200.00 · 76.9%')
  await expect(page.locator('.metric').filter({ hasText: '充电费用占比' })).toContainText('¥60.00 · 23.1%')
  await expect(page.getByText('综合能耗')).toHaveCount(0)
  await expect(page.getByRole('img', { name: '油耗趋势图' })).toBeVisible()
  await expect(page.getByRole('img', { name: '电耗趋势图' })).toBeVisible()
  await expect(page.getByRole('img', { name: '油耗成本趋势图' })).toBeVisible()
  await expect(page.getByRole('img', { name: '电耗成本趋势图' })).toBeVisible()
})

test('keeps the energy page usable without page overflow on a narrow screen', async ({ page }) => {
  await page.setViewportSize({ width: 480, height: 900 })
  await addVehicle(page, '窄屏测试车', 'fuel')
  await addFuelRecord(page, '2026-08-20T10:00', '1500', '25', '125', true)
  await page.goto('/energy')

  await expect(page.getByRole('heading', { name: '能耗统计' })).toBeVisible()
  await expect(page.getByLabel('能耗车辆')).toBeVisible()
  await expect(page.getByRole('table', { name: '补能记录' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  expect(await page.locator('.table-scroll').last().evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true)
  expect(await page.locator('.energy-charts').evaluate(element => getComputedStyle(element).gridTemplateColumns.split(' ').length)).toBe(1)
})


